### ISSUE TITLE
Tutorial on usage with shadow-cljs

### ISSUE THREAD

**Issue by DogLooksGood** [rksm/clj-suitable#2]
It will be nice to be able to use with shadow-cljs.

**Comment by davidpham87** [comment]
Agree for shadow-cljs. Although I use it with emacs Cider, but it failed last time I tried it.

**Comment by rksm** [comment]
Support for shadow-cljs is now implemented. Since suitable is part of CIDER 0.22.0 it's enough to "jack-in" - completions are then computed with suitable and cljs-tooling. I leave this open until I have time to update the README and make a little demo video.

**Comment by davidpham87** [comment]
What about just connect to shadow-cljs, through cider-connect-cljs?

**Comment by rksm** [comment]
Yep, that should work as well. There is no setup code needed, everything will just be dealt with when the editor sends an nrepl completion message. The only reason why shadow-cljs needed special handling at all is that the internals for accessing the cljs repl and compilation environment it different.

**Comment by davidpham87** [comment]
hum... I could not make it work, unfortunately...

**Comment by rksm** [comment]
Thanks for the report!

> By the way, to make it work with cider, you should also add the dependency in your .shadow-cljs.edn file.

You mean when starting the repl not with cider but with `shadow-cljs watch` a la https://shadow-cljs.github.io/docs/UsersGuide.html#nREPL ? Will add this to the readme.

Regarding the bug, can you please share your setup steps? `shadow-cljs watch` and then connect in cider?

Thanks!

**Comment by davidpham87** [comment]
Dear @rksm,

> You mean when starting the repl not with cider but with shadow-cljs watch a la https://shadow-cljs.github.io/docs/UsersGuide.html#nREPL ? Will add this to the readme.

This is exactly what I meant. 

> Regarding the bug, can you please share your setup steps? shadow-cljs watch and then connect in cider?

Exactly my set up. I choose `shadow-select`as option.

**Comment by alendit** [comment]
So, how do you use suitable with shadow-cljs? I tried 

```
npx shadow-cljs -d cider/piggieback:0.4.2 -d cider/cider-nrepl:0.23.0 -d org.rksm/suitable:0.3.2  watch dev
```

but I doesn't appear to do anything.

**Comment by rksm** [comment]
Sorry, for Calva I have no clue, you would need to get in touch with

For cider I just successfully tried the following steps:

1. `npx create-cljs-project suitable-test; cd suitable-test`

2. Create / modify:

`shadow-cljs.edn`

```clj
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 :dev-http {8080 "public"}

 :dependencies
 [[cider/cider-nrepl "RELEASE"]]

 :builds
 {:frontend
  {:target :browser
   :modules {:main {:init-fn foo.main/init}}
   }}}
```

`src/main/foo/main.cljs`

```clj
(ns foo.main)

(defn init []
  (println "Hello World"))
```

`public/index.html`

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>fooo</title>
  </head>
  <body>
    <div id="root">hello</div>
    <script src="/js/main.js"></script>
  </body>
</html>
```

3. `shadow-cljs watch frontend`

output

```
shadow-cljs - config: /home/robert/projects/clojure/2020-01-21_shadow_cljs_issue/suitable-test/shadow-cljs.edn  cli version: 2.8.83  node: v12.13.0
shadow-cljs - HTTP server available at http://localhost:8080
shadow-cljs - server version: 2.8.83 running at http://localhost:9630
shadow-cljs - nREPL server started on port 44617
shadow-cljs - watching build :frontend
[:frontend] Configuring build.
[:frontend] Compiling ...
[:frontend] Build completed. (135 files, 134 compiled, 0 warnings, 6.78s)
...
```

4. Open browser http://localhost:8080

5. `cider-connect-cljs`

-> `shadow-select`
-> select host localhost
-> select port 44617 (should be found by cider automatically, if not see output above)

5. in emacs repl or buffer `(js/document.|)` + completion command should produce sth like

![2020-01-25_suitable_shadow_cljs](https://user-images.githubusercontent.com/467450/73127865-1618fe80-3fc7-11ea-8b5f-89fc17cda54f.png)

Instead of running a repl manually you can also use `cider-jack-in-cljs`.

**Comment by rksm** [comment]
Closing this now, should there be other issues please reopen or file a new issue.
