### ISSUE TITLE
Unwanted side-effects during completion

### ISSUE THREAD

**Issue by thheller** [rksm/clj-suitable#4]
So I looked over the code a bit trying to figure out what is going on in https://github.com/thheller/shadow-cljs/issues/569 and noticed that the completion code just blindly evals everything in its path.

That seems to make it extremely unsafe when doing anything side-effecty?

I tried this with the `rebel-readline` setup described in the README.

```
(-> (js/alert "foo") (.| 
```

press TAB at the `|` and see the browser actually showing the alert before I told it to eval.

Might be intentional but seems kinda worrysome to me.

**Comment by rksm** [comment]
As the readme says, suitable enumerates the properties of values / objects. Code snippet leading up to the expression being typed are attempted to be evaluated and any side effect that might have will occur. If this is worrisome to you then please don't use it.

**Comment by thheller** [comment]
Maybe it should back-off after actual function calls? Meaning it only completes for already realized values?

Dunno just thinking out loud. I don't use this since I use Cursive but I think this as the default behavior may lead to problems and wanted to voice my concerns. Feel free to close this if you don't agree.

**Comment by bbatsov** [comment]
I think it makes sense to mention this in the README, so at least people are aware of the potential problem. Maybe add some caveats section?

**Comment by arichiardi** [comment]
I would definitely add it to cider docs as well.

On a side note, I have always wondered if the Google Closure Compiler could give us some static analysis info on JS objects so that we can avoid eval-ing.

**Comment by rksm** [comment]
So for cider we've added the [cider-enhanced-cljs-completion-p](https://github.com/clojure-emacs/cider-nrepl/issues/648) flag that is mentioned here: https://docs.cider.mx/cider/cljs/configuration.html. This can be made more visible or disabled by default.

The Google closure compiler has more data that could be used for completion but this is not complete and it has not the ability to inspect runtime objects / provide completion for expressions. No doubt, building a completion engine around that can be useful but would only be a subset of suitable.

**Comment by arichiardi** [comment]
And to be fair it would probably be a better fit in something like `clj-kondo` because of its static nature.

We don't want to duplicate parsing engines all over the place. Everything dynamic though for cljs and completions I think should stay in `clj-suitable`.

**Comment by rksm** [comment]
Closing this for now. The warning for unwanted side effects is now clearer in the readme. One thing to think about is to provide a setting as to how "deep" the evaluation can go, as described by @thheller above. I personally wouldn't want to loose the ability to evaluate / complete expr chains but providing this as an option... might be an option.
